
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: 'receiver@mail.com'
        from: 'sender@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'sender@gmail.com'
        auth_password: 'sender-app-password'
        auth_identity: 'sender@gmail.com'
        send_resolved: true
        headers:
          Subject: "[Alert] {{ .Status }} - {{ .CommonLabels.alertname }} - DevOpsProject - TEAM NoBackupNoCry"
