apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-I3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-I3
  template:
    metadata:
      labels:
        app: devops-I3
    spec:
      containers:
      - name: devops-I3
        image: ghcr.io/yoyo53/devops-i3:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: devops-I3
spec:
  type: NodePort
  selector:
    app: devops-I3
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 30001
